import { Injectable } from '@angular/core';
import { LetterPhoto } from './letter-photo';

@Injectable({
  providedIn: 'root'
})
export class LettersService {
  protected letters: LetterPhoto[] = [
    { id: 'A000', letter: 'A', photo: '/assets/watermark/A000.jpg', thumbnail: '/assets/thumbnail/A000.webp', description: 'Boat' },
    { id: 'A001', letter: 'A', photo: '/assets/watermark/A001.jpg', thumbnail: '/assets/thumbnail/A001.webp', description: 'Cardboard Cathedral' },
    { id: 'A002', letter: 'A', photo: '/assets/watermark/A002.jpg', thumbnail: '/assets/thumbnail/A002.webp', description: 'Cone' },
    { id: 'A003', letter: 'A', photo: '/assets/watermark/A003.jpg', thumbnail: '/assets/thumbnail/A003.webp', description: 'Driftwood Ruby Bay' },
    // { id: 'A004', letter: 'A', photo: '/assets/watermark/A004.jpg', thumbnail: '/assets/thumbnail/A004.webp', description: 'Hokitika' },
    { id: 'A005', letter: 'A', photo: '/assets/watermark/A005.jpg', thumbnail: '/assets/thumbnail/A005.webp', description: 'Picnic Table' },
    { id: 'A006', letter: 'A', photo: '/assets/watermark/A006.jpg', thumbnail: '/assets/thumbnail/A006.webp', description: 'Staircase' },
    { id: 'B003', letter: 'B', photo: '/assets/watermark/B003.jpg', thumbnail: '/assets/thumbnail/B003.webp', description: 'Playground' },
    { id: 'B001', letter: 'B', photo: '/assets/watermark/B001.jpg', thumbnail: '/assets/thumbnail/B001.webp', description: 'Biscuits' },
    { id: 'B002', letter: 'B', photo: '/assets/watermark/B002.jpg', thumbnail: '/assets/thumbnail/B002.webp', description: 'Hydrangea' },
    { id: 'B000', letter: 'B', photo: '/assets/watermark/B000.jpg', thumbnail: '/assets/thumbnail/B000.webp', description: 'Bike' },
    { id: 'B004', letter: 'B', photo: '/assets/watermark/B004.jpg', thumbnail: '/assets/thumbnail/B004.webp', description: 'Shells' },
    { id: 'C002', letter: 'C', photo: '/assets/watermark/C002.jpg', thumbnail: '/assets/thumbnail/C002.webp', description: 'Hagley' },
    { id: 'C000', letter: 'C', photo: '/assets/watermark/C000.jpg', thumbnail: '/assets/thumbnail/C000.webp', description: 'Botanic Gardens' },
    // { id: 'C001', letter: 'C', photo: '/assets/watermark/C001.jpg', thumbnail: '/assets/thumbnail/C001.webp', description: 'Gardens' },
    { id: 'C003', letter: 'C', photo: '/assets/watermark/C003.jpg', thumbnail: '/assets/thumbnail/C003.webp', description: 'Rock' },
    { id: 'D000', letter: 'D', photo: '/assets/watermark/D000.jpg', thumbnail: '/assets/thumbnail/D000.webp', description: 'Botanic Gardens' },
    { id: 'D001', letter: 'D', photo: '/assets/watermark/D001.jpg', thumbnail: '/assets/thumbnail/D001.webp', description: 'Canterbury Plains' },
    { id: 'D002', letter: 'D', photo: '/assets/watermark/D002.jpg', thumbnail: '/assets/thumbnail/D002.webp', description: 'Fire Sign' },
    { id: 'D003', letter: 'D', photo: '/assets/watermark/D003.jpg', thumbnail: '/assets/thumbnail/D003.webp', description: 'Sugar Loaf' },
    { id: 'E000', letter: 'E', photo: '/assets/watermark/E000.jpg', thumbnail: '/assets/thumbnail/E000.webp', description: 'Beach' },
    { id: 'E001', letter: 'E', photo: '/assets/watermark/E001.jpg', thumbnail: '/assets/thumbnail/E001.webp', description: 'Flax' },
    { id: 'E002', letter: 'E', photo: '/assets/watermark/E002.jpg', thumbnail: '/assets/thumbnail/E002.webp', description: 'Margaret Mahy' },
    { id: 'F000', letter: 'F', photo: '/assets/watermark/F000.jpg', thumbnail: '/assets/thumbnail/F000.webp', description: 'Beach Godley Head' },
    { id: 'F001', letter: 'F', photo: '/assets/watermark/F001.jpg', thumbnail: '/assets/thumbnail/F001.webp', description: 'Beach' },
    { id: 'F002', letter: 'F', photo: '/assets/watermark/F002.jpg', thumbnail: '/assets/thumbnail/F002.webp', description: 'Sign' },
    { id: 'G000', letter: 'G', photo: '/assets/watermark/G000.jpg', thumbnail: '/assets/thumbnail/G000.webp', description: 'Driftwood_' },
    { id: 'G001', letter: 'G', photo: '/assets/watermark/G001.jpg', thumbnail: '/assets/thumbnail/G001.webp', description: 'Māori Post' },
    { id: 'G002', letter: 'G', photo: '/assets/watermark/G002.jpg', thumbnail: '/assets/thumbnail/G002.webp', description: 'Sand' },
    { id: 'H000', letter: 'H', photo: '/assets/watermark/H000.jpg', thumbnail: '/assets/thumbnail/H000.webp', description: 'Lake Daniels' },
    { id: 'H001', letter: 'H', photo: '/assets/watermark/H001.jpg', thumbnail: '/assets/thumbnail/H001.webp', description: 'Margaret Mahy' },
    { id: 'H002', letter: 'H', photo: '/assets/watermark/H002.jpg', thumbnail: '/assets/thumbnail/H002.webp', description: 'Rugby Post' },
    { id: 'H003', letter: 'H', photo: '/assets/watermark/H003.jpg', thumbnail: '/assets/thumbnail/H003.webp', description: 'Sign view' },
    { id: 'H004', letter: 'H', photo: '/assets/watermark/H004.jpg', thumbnail: '/assets/thumbnail/H004.webp', description: 'Sign' },
    { id: 'I000', letter: 'I', photo: '/assets/watermark/I000.jpg', thumbnail: '/assets/thumbnail/I000.webp', description: 'Cone' },
    { id: 'I001', letter: 'I', photo: '/assets/watermark/I001.jpg', thumbnail: '/assets/thumbnail/I001.webp', description: 'Daffodil' },
    { id: 'I002', letter: 'I', photo: '/assets/watermark/I002.jpg', thumbnail: '/assets/thumbnail/I002.webp', description: 'Rose' },
    { id: 'I003', letter: 'I', photo: '/assets/watermark/I003.jpg', thumbnail: '/assets/thumbnail/I003.webp', description: 'Skytower' },
    { id: 'I004', letter: 'I', photo: '/assets/watermark/I004.jpg', thumbnail: '/assets/thumbnail/I004.webp', description: 'Sugar Loaf' },
    { id: 'I005', letter: 'I', photo: '/assets/watermark/I005.jpg', thumbnail: '/assets/thumbnail/I005.webp', description: 'Waterfall' },
    { id: 'J000', letter: 'J', photo: '/assets/watermark/J000.jpg', thumbnail: '/assets/thumbnail/J000.webp', description: 'Ponamu Statue' },
    { id: 'J001', letter: 'J', photo: '/assets/watermark/J001.jpg', thumbnail: '/assets/thumbnail/J001.webp', description: 'Shells' },
    { id: 'K000', letter: 'K', photo: '/assets/watermark/K000.jpg', thumbnail: '/assets/thumbnail/K000.webp', description: 'Plane' },
    { id: 'K001', letter: 'K', photo: '/assets/watermark/K001.jpg', thumbnail: '/assets/thumbnail/K001.webp', description: 'Sign Flax' },
    { id: 'K002', letter: 'K', photo: '/assets/watermark/K002.jpg', thumbnail: '/assets/thumbnail/K002.webp', description: 'Sign(1)' },
    { id: 'K003', letter: 'K', photo: '/assets/watermark/K003.jpg', thumbnail: '/assets/thumbnail/K003.webp', description: 'Sign' },
    { id: 'L000', letter: 'L', photo: '/assets/watermark/L000.jpg', thumbnail: '/assets/thumbnail/L000.webp', description: 'Botanic Gardens' },
    { id: 'L001', letter: 'L', photo: '/assets/watermark/L001.jpg', thumbnail: '/assets/thumbnail/L001.webp', description: 'Lime scooter beach' },
    { id: 'L002', letter: 'L', photo: '/assets/watermark/L002.jpg', thumbnail: '/assets/thumbnail/L002.webp', description: 'Lime Scooter' },
    { id: 'L003', letter: 'L', photo: '/assets/watermark/L003.jpg', thumbnail: '/assets/thumbnail/L003.webp', description: 'Punt' },
    { id: 'L004', letter: 'L', photo: '/assets/watermark/L004.jpg', thumbnail: '/assets/thumbnail/L004.webp', description: 'Punting' },
    { id: 'M000', letter: 'M', photo: '/assets/watermark/M000.jpg', thumbnail: '/assets/thumbnail/M000.webp', description: 'Art Centre (2)' },
    { id: 'M001', letter: 'M', photo: '/assets/watermark/M001.jpg', thumbnail: '/assets/thumbnail/M001.webp', description: 'Art Centre' },
    { id: 'M002', letter: 'M', photo: '/assets/watermark/M002.jpg', thumbnail: '/assets/thumbnail/M002.webp', description: 'Pier' },
    { id: 'M003', letter: 'M', photo: '/assets/watermark/M003.jpg', thumbnail: '/assets/thumbnail/M003.webp', description: 'Rose Garden' },
    { id: 'N000', letter: 'N', photo: '/assets/watermark/N000.jpg', thumbnail: '/assets/thumbnail/N000.webp', description: 'Lyttelton' },
    { id: 'N001', letter: 'N', photo: '/assets/watermark/N001.jpg', thumbnail: '/assets/thumbnail/N001.webp', description: 'Mapua' },
    { id: 'N002', letter: 'N', photo: '/assets/watermark/N002.jpg', thumbnail: '/assets/thumbnail/N002.webp', description: 'Māpua' },
    { id: 'O000', letter: 'O', photo: '/assets/watermark/O000.jpg', thumbnail: '/assets/thumbnail/O000.webp', description: 'Art Centre' },
    { id: 'O001', letter: 'O', photo: '/assets/watermark/O001.jpg', thumbnail: '/assets/thumbnail/O001.webp', description: 'Gondola' },
    { id: 'O002', letter: 'O', photo: '/assets/watermark/O002.jpg', thumbnail: '/assets/thumbnail/O002.webp', description: 'Kina' },
    { id: 'O003', letter: 'O', photo: '/assets/watermark/O003.jpg', thumbnail: '/assets/thumbnail/O003.webp', description: 'Pier' },
    { id: 'O004', letter: 'O', photo: '/assets/watermark/O004.jpg', thumbnail: '/assets/thumbnail/O004.webp', description: 'Plains' },
    { id: 'O005', letter: 'O', photo: '/assets/watermark/O005.jpg', thumbnail: '/assets/thumbnail/O005.webp', description: 'Rose' },
    { id: 'P000', letter: 'P', photo: '/assets/watermark/P000.jpg', thumbnail: '/assets/thumbnail/P000.webp', description: 'Beach' },
    { id: 'P001', letter: 'P', photo: '/assets/watermark/P001.jpg', thumbnail: '/assets/thumbnail/P001.webp', description: 'Flag Mt Cook' },
    { id: 'P002', letter: 'P', photo: '/assets/watermark/P002.jpg', thumbnail: '/assets/thumbnail/P002.webp', description: 'Laser Kiwi' },
    { id: 'P003', letter: 'P', photo: '/assets/watermark/P003.jpg', thumbnail: '/assets/thumbnail/P003.webp', description: 'Sign of the Takahe' },
    { id: 'Q000', letter: 'Q', photo: '/assets/watermark/Q000.jpg', thumbnail: '/assets/thumbnail/Q000.webp', description: 'Sun Dial' },
    { id: 'Q001', letter: 'Q', photo: '/assets/watermark/Q001.jpg', thumbnail: '/assets/thumbnail/Q001.webp', description: 'Hot Air Balloon' },
    { id: 'R000', letter: 'R', photo: '/assets/watermark/R000.jpg', thumbnail: '/assets/thumbnail/R000.webp', description: ' Bridge of remembrance' },
    { id: 'R001', letter: 'R', photo: '/assets/watermark/R001.jpg', thumbnail: '/assets/thumbnail/R001.webp', description: 'Beach' },
    { id: 'R002', letter: 'R', photo: '/assets/watermark/R002.jpg', thumbnail: '/assets/thumbnail/R002.webp', description: 'Driftwood' },
    { id: 'R003', letter: 'R', photo: '/assets/watermark/R003.jpg', thumbnail: '/assets/thumbnail/R003.webp', description: 'Sumner' },
    { id: 'R004', letter: 'R', photo: '/assets/watermark/R004.jpg', thumbnail: '/assets/thumbnail/R004.webp', description: 'Tannery' },
    { id: 'S000', letter: 'S', photo: '/assets/watermark/S000.jpg', thumbnail: '/assets/thumbnail/S000.webp', description: 'Brighton' },
    { id: 'S001', letter: 'S', photo: '/assets/watermark/S001.jpg', thumbnail: '/assets/thumbnail/S001.webp', description: 'Handle' },
    { id: 'S002', letter: 'S', photo: '/assets/watermark/S002.jpg', thumbnail: '/assets/thumbnail/S002.webp', description: 'Playground' },
    { id: 'S003', letter: 'S', photo: '/assets/watermark/S003.jpg', thumbnail: '/assets/thumbnail/S003.webp', description: 'Road' },
    { id: 'S004', letter: 'S', photo: '/assets/watermark/S004.jpg', thumbnail: '/assets/thumbnail/S004.webp', description: 'Rock' },
    { id: 'S005', letter: 'S', photo: '/assets/watermark/S005.jpg', thumbnail: '/assets/thumbnail/S005.webp', description: 'Roses (2)' },
    { id: 'S006', letter: 'S', photo: '/assets/watermark/S006.jpg', thumbnail: '/assets/thumbnail/S006.webp', description: 'Roses' },
    { id: 'S007', letter: 'S', photo: '/assets/watermark/S007.jpg', thumbnail: '/assets/thumbnail/S007.webp', description: 'Sculpture (1)' },
    { id: 'S008', letter: 'S', photo: '/assets/watermark/S008.jpg', thumbnail: '/assets/thumbnail/S008.webp', description: 'Sculpture' },
    { id: 'S009', letter: 'S', photo: '/assets/watermark/S009.jpg', thumbnail: '/assets/thumbnail/S009.webp', description: 'Slide' },
    { id: 'T000', letter: 'T', photo: '/assets/watermark/T000.jpg', thumbnail: '/assets/thumbnail/T000.webp', description: 'Pier' },
    { id: 'T001', letter: 'T', photo: '/assets/watermark/T001.jpg', thumbnail: '/assets/thumbnail/T001.webp', description: 'Tree' },
    { id: 'T002', letter: 'T', photo: '/assets/watermark/T002.jpg', thumbnail: '/assets/thumbnail/T002.webp', description: 'Whale' },
    { id: 'U000', letter: 'U', photo: '/assets/watermark/U000.jpg', thumbnail: '/assets/thumbnail/U000.webp', description: 'Art Centre' },
    { id: 'U001', letter: 'U', photo: '/assets/watermark/U001.jpg', thumbnail: '/assets/thumbnail/U001.webp', description: 'Hagley Park' },
    { id: 'U002', letter: 'U', photo: '/assets/watermark/U002.jpg', thumbnail: '/assets/thumbnail/U002.webp', description: 'Statue' },
    { id: 'U003', letter: 'U', photo: '/assets/watermark/U003.jpg', thumbnail: '/assets/thumbnail/U003.webp', description: 'Sugar Loaf' },
    { id: 'V000', letter: 'V', photo: '/assets/watermark/V000.jpg', thumbnail: '/assets/thumbnail/V000.webp', description: 'Chalice' },
    { id: 'V001', letter: 'V', photo: '/assets/watermark/V001.jpg', thumbnail: '/assets/thumbnail/V001.webp', description: 'Fountain' },
    { id: 'V002', letter: 'V', photo: '/assets/watermark/V002.jpg', thumbnail: '/assets/thumbnail/V002.webp', description: 'Jandals' },
    { id: 'V003', letter: 'V', photo: '/assets/watermark/V003.jpg', thumbnail: '/assets/thumbnail/V003.webp', description: 'Milford Sound' },
    { id: 'V004', letter: 'V', photo: '/assets/watermark/V004.jpg', thumbnail: '/assets/thumbnail/V004.webp', description: 'Sign of the Takahe' },
    { id: 'W000', letter: 'W', photo: '/assets/watermark/W000.jpg', thumbnail: '/assets/thumbnail/W000.webp', description: 'Avon' },
    { id: 'W001', letter: 'W', photo: '/assets/watermark/W001.jpg', thumbnail: '/assets/thumbnail/W001.webp', description: 'Cones' },
    { id: 'W002', letter: 'W', photo: '/assets/watermark/W002.jpg', thumbnail: '/assets/thumbnail/W002.webp', description: 'Playground' },
    { id: 'X000', letter: 'X', photo: '/assets/watermark/X000.jpg', thumbnail: '/assets/thumbnail/X000.webp', description: 'Bridge of Remembrance' },
    // { id: 'X001', letter: 'X', photo: '/assets/watermark/X001.jpg', thumbnail: '/assets/thumbnail/X001.webp', description: 'Bridge' },
    { id: 'X002', letter: 'X', photo: '/assets/watermark/X002.jpg', thumbnail: '/assets/thumbnail/X002.webp', description: 'Statue' },
    { id: 'X003', letter: 'X', photo: '/assets/watermark/X003.jpg', thumbnail: '/assets/thumbnail/X003.webp', description: 'Sugar Loaf' },
    { id: 'Y000', letter: 'Y', photo: '/assets/watermark/Y000.jpg', thumbnail: '/assets/thumbnail/Y000.webp', description: 'Art Centre' },
    { id: 'Y001', letter: 'Y', photo: '/assets/watermark/Y001.jpg', thumbnail: '/assets/thumbnail/Y001.webp', description: 'Crane' },
    { id: 'Y002', letter: 'Y', photo: '/assets/watermark/Y002.jpg', thumbnail: '/assets/thumbnail/Y002.webp', description: 'Dolphins' },
    { id: 'Y003', letter: 'Y', photo: '/assets/watermark/Y003.jpg', thumbnail: '/assets/thumbnail/Y003.webp', description: 'Mountains' },
    { id: 'Y004', letter: 'Y', photo: '/assets/watermark/Y004.jpg', thumbnail: '/assets/thumbnail/Y004.webp', description: 'Plane' },
    { id: 'Y005', letter: 'Y', photo: '/assets/watermark/Y005.jpg', thumbnail: '/assets/thumbnail/Y005.webp', description: 'Waterfall' },
    { id: 'Y006', letter: 'Y', photo: '/assets/watermark/Y006.jpg', thumbnail: '/assets/thumbnail/Y006.webp', description: 'Wind Turbine' },
    { id: 'Z000', letter: 'Z', photo: '/assets/watermark/Z000.jpg', thumbnail: '/assets/thumbnail/Z000.webp', description: 'Beach' },
    { id: 'Z001', letter: 'Z', photo: '/assets/watermark/Z001.jpg', thumbnail: '/assets/thumbnail/Z001.webp', description: 'Driftwood' },
    { id: 'Z002', letter: 'Z', photo: '/assets/watermark/Z002.jpg', thumbnail: '/assets/thumbnail/Z002.webp', description: 'Pathway' },
  ];
  constructor() { }

  getLetters(): LetterPhoto[] {
    return this.letters;
  }

  getLetterById(id: string): LetterPhoto | undefined {
    return this.letters.find(letter => letter.id === id);
  }

  getLettersByLetter(letter: string): LetterPhoto[] {
    return this.letters.filter(l => l.letter === letter);
  }
}
